setting aplikasi - warna tema admin
OpenSID/OpenKab pull request #127
Opened 2023-04-17 22:07 UTC by FirlianiF

https://github.com/OpenSID/OpenKab/issues/44

2023-04-18 03:20 UTC, andifahruddinakas commented
Gunakan asset cdn, https://cdnjs.com/libraries/bootstrap-colorpicker

2023-04-25 03:57 UTC, andifahruddinakas requested changes
@FirlianiF, buat lebih umum karena selanjutnya akan ada pengaturan lainnya. Sehingga kedepan untuk perubahan lebih gampang.

Ambil data dari api dan tampilkan menggunakan ajax/alpin.js

2023-04-25 03:57 UTC, andifahruddinakas commented on vendor/jeroennoten/laravel-adminlte/resources/views/master.blade.php
> +</html>
@FirlianiF, jangan ikutkan file ini

2023-04-26 08:31 UTC, andifahruddinakas commented
tambahkan ke menu ini.
<img width="123" alt="image" src="https://user-images.githubusercontent.com/57283157/234517334-6518d3f5-d3a8-496c-a29f-97d2ec5564f1.png">

2023-04-27 05:11 UTC, FirlianiF commented
Noted mas @andifahruddinakas

2023-05-06 01:27 UTC, FirlianiF commented
Diganti ke PR https://github.com/OpenSID/OpenKab/pull/159

2023-05-06 01:27 UTC, closed without merging