Filter statistik Penduduk
OpenSID/OpenKab pull request #133
Opened 2023-04-27 02:50 UTC by apidong

issue https://github.com/OpenSID/OpenKab/issues/120

untuk modul statistik yang lain issue perlu di pecah berdasarkan modul, karena terlalu banyak yang harus dirubah

2023-04-27 04:19 UTC, andifahruddinakas commented
Mas @apidong, untuk filter alurnya seragamkan dengan yang lain.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/57283157/234758195-e8dbbae4-1f03-402a-98fc-d8dda1c678ac.png">
Seperti
<img width="539" alt="image" src="https://user-images.githubusercontent.com/57283157/234758296-1697c474-37d5-4fe8-af2a-23da43ba9973.png">

2023-04-27 04:23 UTC, andifahruddinakas requested changes

2023-04-27 04:23 UTC, andifahruddinakas commented on app/Http/Controllers/Api/StatistikController.php
> +            // dd($penduduk->listStatistik($this->kategori));
```suggestion
```

2023-04-27 04:23 UTC, andifahruddinakas commented on resources/views/statistik/index.blade.php
> +                                <option value="12">Desember</option>
Dibuat helper saja, cek helper bulan() bisa dimodifikasi jika tidak ada paramter (null) return semua bulan beserta keynya..

2023-04-27 18:07 UTC, apidong commented
@andifahruddinakas @vickyrolanda siap riview ulang

2023-04-29 19:04 UTC, andifahruddinakas commented
mas @apidong, setelah dicek, filter tidak mempengaruhi juga apa yang akan dicetak.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/57283157/235319915-c6a1e104-1607-4327-b244-62ac05cc7b83.png">

<img width="956" alt="image" src="https://user-images.githubusercontent.com/57283157/235319930-91edb2b4-24ec-4c91-8903-7a0766f21468.png">

Yang lain sudah saya rasa sudah ok, bisa di cek ulang mas @vickyrolanda.

2023-04-30 21:50 UTC, apidong commented
siap riview @vickyrolanda

2023-05-02 08:02 UTC, merged