filter statistik keluarga
OpenSID/OpenKab pull request #140
Opened 2023-04-28 16:34 UTC by scqolbu24

solusi untuk issue https://github.com/OpenSID/OpenKab/issues/135

2023-04-29 19:06 UTC, andifahruddinakas commented
mas @scqolbu24, karena menggunakan sumber yang sama. maka https://github.com/OpenSID/OpenKab/pull/133#issuecomment-1528851867 mempengaruhi juga PR ini.

2023-04-29 23:15 UTC, scqolbu24 commented
siap mas @andifahruddinakas

2023-05-02 14:11 UTC, scqolbu24 commented
> Mas @scqolbu24, masih terjadi error berikut :
> 
> * [ ]  <img alt="image" width="960" src="https://user-images.githubusercontent.com/57283157/235621139-b2803e8f-a1c2-4885-9427-15170a96bbfe.png">
> * Sesuaikan dengan PR [Filter statistik Penduduk #133](https://github.com/OpenSID/OpenKab/pull/133) yang sudah digabungkan

@andifahruddinakas saya konfirmasi ke mas @vickyrolanda katanya terkait datanya dibuat beda issue mas, untuk perbedaan data tersebut saya tanyakan di issue https://github.com/OpenSID/OpenKab/issues/135 dan jawaban konfirmasinya baru lewat chat telegram, sepertinya issuenya belum dibuat.

2023-05-04 00:53 UTC, andifahruddinakas requested changes

2023-05-04 00:53 UTC, andifahruddinakas commented on app/Http/Repository/PendudukRepository.php
> +                ->toBoundSql();
Mas @scqolbu24, saya coba akses melalui postman dari perubahan di PR ini hasilnya sbb:
```
{
    "message": "Call to undefined method App\\Models\\Keluarga::logKeluarga()",
    "exception": "BadMethodCallException",
    "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\ForwardsCalls.php",
    "line": 71,
    "trace": [
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\ForwardsCalls.php",
            "line": 36,
            "function": "throwBadMethodCallException",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "::"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php",
            "line": 2330,
            "function": "forwardCallTo",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\QueriesRelationships.php",
            "line": 864,
            "function": "__call",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Relations\\Relation.php",
            "line": 104,
            "function": "Illuminate\\Database\\Eloquent\\Concerns\\{closure}",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\QueriesRelationships.php",
            "line": 865,
            "function": "noConstraints",
            "class": "Illuminate\\Database\\Eloquent\\Relations\\Relation",
            "type": "::"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\QueriesRelationships.php",
            "line": 39,
            "function": "getRelationWithoutConstraints",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\QueriesRelationships.php",
            "line": 152,
            "function": "has",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\app\\Http\\Repository\\KeluargaRepository.php",
            "line": 95,
            "function": "whereHas",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\app\\Http\\Repository\\KeluargaRepository.php",
            "line": 40,
            "function": "caseKelasSosial",
            "class": "App\\Http\\Repository\\KeluargaRepository",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\app\\Http\\Controllers\\Api\\StatistikController.php",
            "line": 65,
            "function": "listStatistik",
            "class": "App\\Http\\Repository\\KeluargaRepository",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php",
            "line": 54,
            "function": "keluarga",
            "class": "App\\Http\\Controllers\\Api\\StatistikController",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
            "line": 43,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 260,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 205,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 798,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 141,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php",
            "line": 50,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 180,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php",
            "line": 126,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php",
            "line": 102,
            "function": "handleRequest",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php",
            "line": 54,
            "function": "handleRequestUsingNamedLimiter",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 180,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\sanctum\\src\\Http\\Middleware\\EnsureFrontendRequestsAreStateful.php",
            "line": 25,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 141,
            "function": "Laravel\\Sanctum\\Http\\Middleware\\{closure}",
            "class": "Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful",
            "type": "->"
        },
        {
            "file": "D:\\PROJECT OPENDESA\\OpenKab\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline. [...]

2023-05-10 03:52 UTC, merged