api statistik berita
OpenSID/OpenKab pull request #144
Opened 2023-04-29 18:34 UTC by FirlianiF

https://github.com/OpenSID/OpenKab/issues/39

https://github.com/OpenSID/OpenKab/issues/40

2023-04-29 20:00 UTC, andifahruddinakas requested changes

2023-04-29 20:00 UTC, andifahruddinakas commented on app/Http/Repository/DasborRepository.php
> +            'statistik_berita' => $this->statistikBerita(),
Ini dipisah, jangan ikut disini, karena bagian ini khusus agregat saja bukan data keseluruhan.

2023-04-29 20:28 UTC, FirlianiF commented on app/Http/Repository/DasborRepository.php
> +            'statistik_berita' => $this->statistikBerita(),
sudah diupdate mas

2023-05-04 01:32 UTC, andifahruddinakas commented
mba @FirlianiF, 

- [ ] cek fungsi filter ini duplikasi : 

<img width="246" alt="image" src="https://user-images.githubusercontent.com/57283157/236087819-f4766fcb-fce4-4e42-a3bc-4fc6a51ae301.png">

dengan filter 
<img width="208" alt="image" src="https://user-images.githubusercontent.com/57283157/236087913-770c21ce-7830-4c79-ac09-33993ec0fe40.png">

untuk wilayah, bisa gunakan filter yang sudah disediakan tsb, krn filternya sudah berdasarkan tingkatan kecamatan.

- [ ] Tambahkan class padat untuk merapikan tampilan kolom no dan jumlah artikel
<img width="727" alt="image" src="https://user-images.githubusercontent.com/57283157/236088517-88403724-149c-4a8f-9f90-2c0c49738a24.png">


- [ ] Selain nama kelurahan, perlu ditampilkan juga nama kecamatannya.
- [ ] Untuk filter berdsarkan kategori dihapus saja, selanjutnya filter tsb dipindahkan ke master > kategori artikel (issue baru) dan ditambahkan jumlah artikel tiap kategori.


Untuk yang lain sudah ok.

2023-05-04 01:37 UTC, FirlianiF commented
Baik noted mas

2023-05-06 00:58 UTC, FirlianiF commented
Sudah diperbaiki, dicek mas @andifahruddinakas

2023-05-08 01:58 UTC, andifahruddinakas commented
@FirlianiF, cek perubahan https://github.com/OpenSID/OpenKab/pull/144/commits/16110acbc7b81f8e097efe600d367e9db9a70739

2023-05-08 01:58 UTC, merged