Pengaturan aplikasi
OpenSID/OpenKab pull request #159
Opened 2023-05-06 01:26 UTC by FirlianiF

https://github.com/OpenSID/OpenKab/issues/44

https://github.com/OpenSID/OpenKab/issues/158

2023-05-08 06:27 UTC, andifahruddinakas requested changes

2023-05-08 06:27 UTC, andifahruddinakas commented on app/Models/Pengaturan.php
> +
Extend to BaseModel

2023-05-08 06:27 UTC, andifahruddinakas commented on app/Http/Requests/PengaturanRequest.php
> +
rules value required

2023-05-08 06:27 UTC, andifahruddinakas commented on resources/views/dasbor/index.blade.php
> +                                        value="@if (session()->has('desa')) {{ session('desa.id') }} @endif">4
hapus `4`

2023-05-08 06:27 UTC, andifahruddinakas commented on resources/views/dasbor/index.blade.php
> +            $('#bulan').select2();
tidak ada kaitannya dengan PR ini

2023-05-08 06:27 UTC, andifahruddinakas commented on resources/views/dasbor/index.blade.php
> +    </script>
tidak ada kaitannya dengan PR ini

2023-05-08 06:36 UTC, andifahruddinakas commented
Menampilkan validasi bisa ikuti cara pada modul master data> bantuan

2023-05-08 07:35 UTC, FirlianiF commented
> Menampilkan validasi bisa ikuti cara pada modul master data> bantuan

sudah mas

2023-05-10 18:45 UTC, andifahruddinakas commented
Mba @FirlianiF, saya cek : 
1. inputan selalu ada warning (border merah dan peringatan)
<img width="545" alt="image" src="https://github.com/OpenSID/OpenKab/assets/57283157/31fd27bb-f5dd-4893-afb8-7434aeb3c304">

2. tidak bisa menggunakan element colorpicker (diklik tidak bisa)
<img width="667" alt="image" src="https://github.com/OpenSID/OpenKab/assets/57283157/39ff17fd-b986-485b-8242-810606c5b48a">

2023-05-15 07:26 UTC, andifahruddinakas commented
mba @FirlianiF, cek perubahan dari commit https://github.com/OpenSID/OpenKab/pull/159/commits/e476f8230681217580370538908033fe9466b2bc

2023-05-15 07:27 UTC, merged

2023-05-15 07:45 UTC, FirlianiF commented
> mba @FirlianiF, cek perubahan dari commit [e476f82](https://github.com/OpenSID/OpenKab/commit/e476f8230681217580370538908033fe9466b2bc)
> 
> untuk saat ini walaupun sudah menggunakan alpin js, namun saat menampilkan form nya masih statis. untuk selanjutnya jika ada penambahan pengaturan perlu disesuaikan ulang.

Baik noted mas.